# Experiment D6: Scale then downsampling (aug→DS)
work_dir: ./work_dir/experiments/D6/
google_drive_dir: ''
sync_to_drive: false
device: 0
phase: train
save_interval: 1
random_seed: 123
eval_interval: 1
log_interval: 100
evaluate_tool: sclite

feeder: SkeletonFeeder
dataset: bisindo
num_worker: 2
feeder_args:
  setting: si
  datatype: skeleton
  split: &split [21, 42]
  used_part: &used_part ['hand21']
  augmentation_types: ['Scale']
  downsampling: true
  downsampling_position: after
  downsampling_ratio: 0.5
  norm_point: [0, 21]

model: TwoStream_Cosign
model_args:
  visual_args:
    in_channels: 2
    split: *split
    temporal_kernel: 5
    hidden_size: 1024
    modes: *used_part
    level: '1'
    adaptive: true
    CR_args:
      clip_length: 25
      ratio: 0.2
  conv_type: K3-P2-K3-P2
  loss_weights:
    CR_ConvCTC_static: 1.0
    CR_SeqCTC_static: 1.0
    CR_Conv_static: 2.0
    CR_Seq_static: 2.0
    CR_ConvCTC_motion: 1.0
    CR_SeqCTC_motion: 1.0
    CR_Conv_motion: 2.0
    CR_Seq_motion: 2.0
    CR_ConvCTC_fusion: 1.0
    CR_SeqCTC_fusion: 1.0
    CR_Conv_fusion: 2.0
    CR_Seq_fusion: 2.0
  norm_scale: 32

batch_size: 4
test_batch_size: 1
optimizer_args:
  base_lr: 0.0004
  learning_ratio: 1
  nesterov: false
  optimizer: AdamW
  start_epoch: 0
  step: [20, 35]
  weight_decay: 0.0001
num_epoch: 40